### ISSUE TITLE
Feat: add response_model for each endpoints

### ISSUE THREAD

**Issue by tokitouq** [tokitouq/manga-api#165]
Create a pydantic model and follow this:
https://fastapi.tiangolo.com/tutorial/response-model/

**Comment by code-master-ajay** [comment]
Hi @tokitouq can i take this up ?

**Comment by tokitouq** [comment]
Hello @code-master-ajay 
>Hi @tokitouq can i take this up ?

Of course, please lmk if you have any doubts :)
Also add different model for `search` and `manga` endpoints.

P.S: you are welcome to tweak properties of each providers to sync with model.

**Comment by tokitouq** [comment]
@code-master-ajay  want me to assign this to you?

**Comment by code-master-ajay** [comment]
@tokitouq yes please.

**Comment by tokitouq** [comment]
@code-master-ajay Hi, do you have any ETA on this?
Cause I'm planning to do some other refactoring based on this.
LMK

**Comment by code-master-ajay** [comment]
Hi @tokitouq, i am really sorry I got caught up in some other work. Can you give me a couple of days to finish this ?
If not,  feel free to assign it to someone else.

**Comment by tokitouq** [comment]
@code-master-ajay Hi, well I guess you're busy with your works. sorry I fixed this myself.
anyways appreciate your interest :sparkles:
